language: crystal

before_install:
  - curl -R -O http://www.lua.org/ftp/lua-5.3.4.tar.gz
  - tar zxf lua-5.3.4.tar.gz
  - cd lua-5.3.4
  - sudo make linux install
  - cd ../

script:
  - shards install
  - crystal spec
  - bin/ameba
